<<<<<<< HEAD
name: Docker CI/CD Pipeline
=======
name: Engr Makua Portfolio
>>>>>>> 5b44c8fb5210a7eba874ac7a9397c45728d93bdd

on:
  push:
    branches:
<<<<<<< HEAD
      - main  # change to your default branch if different

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t engrmakua/testrepo:latest

    - name: Tag Docker image
      run: |
      
        docker tag engrmakua/testrepo:latest engrmakua/testrepo:${{ github.sha }}

    - name: Push Docker image (latest and sha)
      run: |
       
        docker engrmakua/testrepo:latest
        docker engrmakua/testrepo:${{ github.sha }}

    # Optional: Run container (for test/stage/demo purposes)
    - name: Run container
      run: |
        docker run -d -p 20:80 --name portfolio_container engrmakua/testrepo:latest

=======
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v3

      - name: Upload static content
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          output_location: "/"
>>>>>>> 5b44c8fb5210a7eba874ac7a9397c45728d93bdd
